-- Run this ONCE after prisma migrate deploy
-- Seeds products and initializes order counter

INSERT INTO "OrderCounter" (id, count) VALUES (1, 0) ON CONFLICT DO NOTHING;

-- Products (price in MXN cents)
INSERT INTO "Product" (id, slug, name, description, "fullDescription", benefits, application, presentation, type, category, image, "priceMxn", stock, active, "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'baktillis',        'Baktillis',         'Fungicida microbiológico a base de Bacillus subtilis de amplio espectro.',                    'Baktillis es un fungicida microbiológico con Bacillus subtilis de alta concentración. Control preventivo y curativo de hongos y bacterias fitopatógenas.', ARRAY['Control de hongos y bacterias','Acción preventiva y curativa','Compatible con manejo integrado','Sin periodo de carencia'], 'Aplicar 1-2 L/ha en aspersión foliar o drench.', 'Suspensión concentrada 1L',     'Suspensión concentrada',          'FUNGICIDAS',        '/images/products/baktillis.png',          36000,  200, true, now(), now()),
  (gen_random_uuid(), 'natucontrol',       'NatuControl',        'Fungicida biológico a base de Trichoderma harzianum para patógenos del suelo.',               'NatuControl con Trichoderma harzianum protege raíces contra Rhizoctonia, Fusarium y Pythium.',                                                              ARRAY['Control de hongos del suelo','Mejora sistema radicular','Apto para orgánico','Efecto prolongado'],              'Aplicar 400-800g/ha al trasplante.',            'Polvo humectable 400g',          'Polvo humectable',                'FUNGICIDAS',        '/images/products/natucontrol-new.png',    58000,  150, true, now(), now()),
  (gen_random_uuid(), 'alteza',            'Alteza',             'Inoculante bioprotector radicular con consorcio de microorganismos benéficos.',               'Alteza combina Bacillus subtilis, Trichoderma asperellum y Pseudomonas fluorescens para bioprotección radicular.',                                          ARRAY['Bioprotección radicular','Triple acción microbiana','Estimulación crecimiento','Certificado orgánico'],          'Aplicar 500g/ha en semilla o trasplante.',      'Polvo humectable 500g',          'Polvo humectable — Inoculante',   'FUNGICIDAS',        '/images/products/alteza.png',             75000,  100, true, now(), now()),
  (gen_random_uuid(), 'nemagyne',          'Nemagyne',           'Coadyuvante nematicida con biopolímeros y extractos botánicos.',                             'Nemagyne actúa como potenciador del control de nematodos con extractos botánicos bioactivados.',                                                              ARRAY['Control complementario nematodos','Biopolímeros naturales','Compatible biológicos','Sin residuos'],              'Aplicar 1-2 L/ha en drench o fertirriego.',    'Concentrado emulsionable 1L',   'Concentrado emulsionable',        'FUNGICIDAS',        '/images/products/nemagyne.png',           55000,  80,  true, now(), now()),
  (gen_random_uuid(), 'nemakron',          'Nemakron',           'Fungicida nematicida biológico con consorcio de hongos entomopatógenos.',                    'Nemakron combina Pochonia chlamydosporia, Paecilomyces lilacinus, extracto de yuca y quitina.',                                                             ARRAY['Control nematodos','Múltiples modos acción','Mejora estructura suelo','Orgánico'],                                'Incorporar 1-2 kg/ha antes de siembra.',        'Polvo humectable 1kg',           'Polvo humectable',                'FUNGICIDAS',        '/images/products/nemakron.png',           0,      120, true, now(), now()),
  (gen_random_uuid(), 'bac-ilia',          'Bac Ilia',           'Fungicida microbiológico a base de Bacillus subtilis.',                                      'Bac Ilia protege contra mildiu, tizón tardío, botrytis y enfermedades fúngicas foliares.',                                                                  ARRAY['Bacillus subtilis alta pureza','Preventivo y curativo','OMRI Listed','Compatible bioestimulantes'],               'Aplicar 2-4 mL/L foliar cada 7-10 días.',       'Suspensión concentrada 1L',     'Suspensión concentrada',          'FUNGICIDAS',        '/images/products/bac-ilia.png',           0,      90,  true, now(), now()),
  (gen_random_uuid(), 'aba-krone',         'Aba Krone',          'Insecticida a base de Abamectina 1.8% para ácaros y trips.',                                'Aba Krone actúa por contacto e ingestión sobre araña roja, trips y minadores de hoja.',                                                                      ARRAY['Amplio espectro','Control ácaros y trips','Contacto e ingestión','Rápida acción'],                                'Aplicar 0.5-1 L/ha al detectar plaga.',         'Concentrado emulsionable 1L',   'Concentrado emulsionable',        'BIOINSECTICIDAS',   '/images/products/abakrone.png',           50000,  180, true, now(), now()),
  (gen_random_uuid(), 'ajick',             'Ajick',              'Repelente botánico a base de extracto de ajo (Allium sativum).',                             'Ajick con extracto esencial de ajo 87% repele insectos y ácaros. OMRI Listed, apto para orgánico.',                                                           ARRAY['Repelente natural','Sin toxicidad humanos','Compatible enemigos naturales','OMRI Listed'],                         'Aplicar 1-2 L/ha cada 5-7 días.',              'Solución acuosa 1L',             'Solución acuosa',                 'BIOINSECTICIDAS',   '/images/products/ajick-new.png',          24000,  250, true, now(), now()),
  (gen_random_uuid(), 'ak-neem',           'AK-Neem',            'Insecticida botánico con Alicina y Capsaicina de amplio espectro.',                          'AK-Neem combina Alicina 67% y Capsaicina 3.5% para control de moscas blancas, pulgones y trips.',                                                           ARRAY['Doble modo acción','Alicina + Capsaicina','Control moscas blancas','Sin periodo carencia'],                       'Aplicar 1-2 L/ha cada 7-10 días.',             'Concentrado emulsionable 1L',   'Concentrado emulsionable',        'BIOINSECTICIDAS',   '/images/products/ak-neem.png',            0,      110, true, now(), now()),
  (gen_random_uuid(), 'azanim',            'Azaním',             'Insecticida botánico a base de Azadiractina 3% (Neem).',                                    'Azaním con Azadiractina 3% controla moscas blancas, pulgones, trips y orugas. Sin resistencias.',                                                            ARRAY['Azadiractina 3%','Múltiples plagas','Acción ovicida','Bajo impacto ambiental'],                                   'Aplicar 0.5-1 L/ha cubriendo bien follaje.',   'Concentrado emulsionable 1L',   'Concentrado emulsionable',        'BIOINSECTICIDAS',   '/images/products/azanim-new.png',         63000,  130, true, now(), now()),
  (gen_random_uuid(), 'glumix',            'Glumix',             'Inoculante a base de hongos endomicorrízicos VAM.',                                         'Glumix con 20,000 esporas viables/kg mejora absorción de fósforo, agua y micronutrientes. Premio Nacional de Innovación.',                                      ARRAY['20,000 esporas/kg','Mayor absorción fósforo','Resistencia estrés hídrico','Premio Nacional'],                    'Incorporar 1-2 kg/ha antes de siembra.',        'Polvo inoculante 1kg',           'Polvo — Inoculante',              'BIOFORTIFICANTES',  '/images/products/glumix-new.png',         33000,  200, true, now(), now()),
  (gen_random_uuid(), 'glumix-irrigation', 'Glumix Irrigation',  'Bioactivador radicular con micorrizas, ácidos húmicos y fúlvicos.',                         'Glumix Irrigation combina micorrizas 20%, ácidos húmicos/fúlvicos 20%, extracto Ascophyllum nodosum 8%. Premio Innovagro.',                                    ARRAY['Compatible fertirriego','Múltiples biostimuentes','Ácidos húmicos','Premio Innovagro'],                           'Aplicar 1-2 kg/ha vía fertirriego.',            'Sólido granulado 1kg',           'Sólido — Inoculante',             'BIOFORTIFICANTES',  '/images/products/glumix-irrigation.png',  80000,  160, true, now(), now()),
  (gen_random_uuid(), 'azseed',            'AZSeed',             'Inoculante de semillas con bacterias fijadoras de nitrógeno.',                              'AZSeed con Azospirillum, Azotobacter, Rhizobium y Bacillus mejora germinación y vigor inicial.',                                                              ARRAY['Fijación nitrógeno','Mejor germinación','Múltiples cepas','OMRI Listed'],                                         'Aplicar 100g por 50 kg semilla.',              'Polvo humectable 100g',          'Polvo humectable — Inoculante',   'BIOFORTIFICANTES',  '/images/products/azseed-new.png',         21000,  300, true, now(), now()),
  (gen_random_uuid(), 'amikrone-1l',       'Amikrone 1L',        'Fertilizante orgánico líquido a base de L-Aminoácidos libres.',                             'Amikrone con materia orgánica 90.73% y perfil completo de L-Aminoácidos estimula metabolismo vegetal.',                                                        ARRAY['90.73% materia orgánica','L-Aminoácidos completos','Microelementos','Estimulación metabolismo'],                  'Dosis foliar 1-2 mL/L o fertirrigación 3-5 L/ha.', 'Líquido concentrado 1L',   'Líquido — Fertilizante orgánico', 'BIOFORTIFICANTES',  '/images/products/amikrone.png',           31000,  220, true, now(), now()),
  (gen_random_uuid(), 'amikrone-500ml',    'Amikrone 500mL',     'Presentación 500mL del fertilizante orgánico L-Aminoácidos.',                              'Amikrone 500mL misma fórmula concentrada. Ideal para productores con menor superficie.',                                                                     ARRAY['Presentación 500mL','Misma fórmula concentrada','L-Aminoácidos','Fácil dosificación'],                           'Dosis foliar 1-2 mL/L o fertirrigación 3-5 L/ha.', 'Líquido concentrado 500mL','Líquido — Fertilizante orgánico', 'BIOFORTIFICANTES',  '/images/products/amikrone-500ml.png',     16800,  280, true, now(), now()),
  (gen_random_uuid(), 'bioelicitor',       'BioElicitor',        'Fertilizante orgánico a base de extracto de algas marinas con citocininas.',               'BioElicitor con Ascophyllum nodosum activa defensas, mejora cuajado y tolerancia al estrés. Hecho en Irlanda.',                                              ARRAY['Ascophyllum nodosum','Citocininas naturales','Mejora cuajado','Activador defensas'],                              'Aplicar 1-2 L/ha cada 10-15 días.',            'Líquido concentrado 1L',         'Líquido — Fertilizante orgánico', 'BIOFORTIFICANTES',  '/images/products/bio-elicitor.png',       32200,  190, true, now(), now())
ON CONFLICT (slug) DO NOTHING;
