import { Product } from "@/components/product-card"

export const productsData: Product[] = [
  // FUNGICIDAS (Biofungicidas, Bactericidas y Nematicidas)
  {
    id: "1",
    name: "Baktilis",
    slug: "baktilis",
    presentation: "Suspension concentrada 1L",
    type: "Suspension concentrada",
    description: "Biofungicida y bactericida de amplio espectro para el control de enfermedades causadas por hongos y bacterias fitopatogenas.",
    fullDescription: "Baktilis es un biofungicida y bactericida de amplio espectro formulado con cepas seleccionadas de Bacillus subtilis. Su accion multisitio permite el control efectivo de enfermedades causadas por hongos y bacterias fitopatogenas en diversos cultivos. Actua por competencia, antibiosis y activacion de las defensas naturales de la planta.",
    benefits: ["Control de hongos y bacterias", "Accion preventiva y curativa", "Compatible con manejo integrado", "Sin periodo de carencia"],
    application: "Aplicar de forma preventiva o a los primeros sintomas. Dosis: 1-2 L/ha en aspersion foliar o drench.",
    category: "FUNGICIDAS",
    image: "/images/products/baktilis.jpg",
  },
  {
    id: "2",
    name: "NatuControl",
    slug: "natucontrol",
    presentation: "Polvo humectable 400g",
    type: "Polvo humectable",
    description: "Nematicida biologico para el control de nematodos fitoparasitos en cultivos de alto valor.",
    fullDescription: "NatuControl es un nematicida biologico a base de Paecilomyces lilacinus, un hongo que parasita huevos y hembras de nematodos fitoparasitos. Ideal para el manejo de Meloidogyne, Pratylenchus y otros generos de nematodos que afectan raices de cultivos de alto valor.",
    benefits: ["Control de nematodos del suelo", "Mejora el sistema radicular", "Seguro para cultivos organicos", "Efecto prolongado"],
    application: "Aplicar al suelo al momento del trasplante o durante el desarrollo del cultivo. Dosis: 400g-800g/ha.",
    category: "FUNGICIDAS",
    image: "/images/products/natucontrol.jpg",
  },
  {
    id: "3",
    name: "BioCopper",
    slug: "biocopper",
    presentation: "Granulos dispersables 1kg",
    type: "Granulos dispersables",
    description: "Fungicida cuprico de origen biologico para la prevencion y control de enfermedades fungicas.",
    fullDescription: "BioCopper es un fungicida a base de cobre complejado con aminoacidos de origen natural. Su formulacion permite una rapida absorcion y distribucion en los tejidos vegetales, brindando proteccion contra mildiu, tizones, manchas foliares y otras enfermedades fungicas.",
    benefits: ["Rapida absorcion", "Bajo riesgo de fitotoxicidad", "Accion preventiva", "Compatible con biologicos"],
    application: "Aplicar preventivamente cada 7-14 dias segun presion de la enfermedad. Dosis: 1-2 kg/ha.",
    category: "FUNGICIDAS",
    image: "/images/products/biocopper.jpg",
  },
  {
    id: "4",
    name: "BioCopper Mix Pro",
    slug: "biocopper-mix-pro",
    presentation: "Granulos dispersables 1kg",
    type: "Granulos dispersables",
    description: "Formulacion mejorada con accion sistemica y de contacto para maxima proteccion contra fitopatogenos.",
    fullDescription: "BioCopper Mix Pro combina cobre complejado con extractos vegetales y microorganismos beneficos para una proteccion integral. Su doble modo de accion sistemico y de contacto brinda maxima proteccion contra un amplio rango de fitopatogenos.",
    benefits: ["Doble modo de accion", "Proteccion de larga duracion", "Fortalece defensas naturales", "Excelente adherencia"],
    application: "Aplicar en rotacion con otros fungicidas. Dosis: 1-1.5 kg/ha cada 10-14 dias.",
    category: "FUNGICIDAS",
    image: "/images/products/biocopper-mix-pro.jpg",
  },
  // BIOFORTIFICANTES (Biofortificantes y Bioestimulantes)
  {
    id: "5",
    name: "Glumix Migration",
    slug: "glumix-migration",
    presentation: "Solido 1kg",
    type: "Solido granulado",
    description: "Biofortificante con microorganismos beneficos que mejora la absorcion de nutrientes y fortalece el sistema radicular.",
    fullDescription: "Glumix Migration es un biofortificante granulado que contiene una mezcla de micorrizas y bacterias promotoras del crecimiento. Estos microorganismos establecen simbiosis con las raices, mejorando la absorcion de agua y nutrientes, especialmente fosforo y microelementos.",
    benefits: ["Mayor absorcion de nutrientes", "Desarrollo radicular superior", "Resistencia a estres hidrico", "Mejora estructura del suelo"],
    application: "Incorporar al suelo antes de la siembra o trasplante. Dosis: 1-2 kg/ha.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/glumix-migration.jpg",
  },
  {
    id: "6",
    name: "Glumix",
    slug: "glumix",
    presentation: "Polvo 1kg",
    type: "Polvo soluble",
    description: "Bioestimulante a base de aminoacidos y extractos vegetales que promueve el crecimiento y desarrollo vegetal.",
    fullDescription: "Glumix es un bioestimulante de alto rendimiento formulado con aminoacidos libres, acido humico y extractos de algas marinas. Estimula el metabolismo vegetal, promueve la floracion, mejora el cuajado de frutos y aumenta la tolerancia a estres abiotico.",
    benefits: ["Estimula crecimiento", "Mejora floracion y cuajado", "Aumenta rendimientos", "Reduce estres"],
    application: "Aplicar foliarmente o en fertirrigacion. Dosis foliar: 2-3 g/L. Fertirrigacion: 1-2 kg/ha.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/glumix.jpg",
  },
  {
    id: "7",
    name: "AZSeed",
    slug: "azseed",
    presentation: "Polvo humectable 100g",
    type: "Polvo humectable",
    description: "Tratamiento de semillas con bacterias fijadoras de nitrogeno para mejorar la germinacion y vigor inicial.",
    fullDescription: "AZSeed es un inoculante de semillas a base de Azospirillum brasilense, una bacteria fijadora de nitrogeno atmosferico. Mejora la germinacion, vigor inicial y desarrollo radicular de plantulas, reduciendo la dependencia de fertilizantes nitrogenados.",
    benefits: ["Fijacion de nitrogeno", "Mejor germinacion", "Plantulas mas vigorosas", "Ahorro en fertilizantes"],
    application: "Aplicar directamente a las semillas antes de la siembra. Dosis: 100g por cada 50 kg de semilla.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/azseed.jpg",
  },
  {
    id: "8",
    name: "AmiTone",
    slug: "amitone",
    presentation: "Liquido 1L",
    type: "Liquido concentrado",
    description: "Bioestimulante foliar rico en aminoacidos libres que mejora la respuesta a condiciones de estres.",
    fullDescription: "AmiTone es un bioestimulante liquido con alta concentracion de aminoacidos libres de rapida absorcion. Mejora la respuesta del cultivo ante condiciones de estres termico, hidrico o salino, acelerando la recuperacion y manteniendo el rendimiento productivo.",
    benefits: ["Rapida absorcion", "Reduce estres termico", "Mejora recuperacion", "Compatible con agroquimicos"],
    application: "Aplicar foliarmente en etapas criticas o despues de estres. Dosis: 1-2 L/ha.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/amitone.jpg",
  },
  {
    id: "9",
    name: "BioElicitor",
    slug: "bioelicitor",
    presentation: "Liquido 1L",
    type: "Liquido concentrado",
    description: "Activador de defensas naturales de la planta que induce resistencia sistemica adquirida.",
    fullDescription: "BioElicitor contiene elicitores naturales que activan los mecanismos de defensa propios de la planta. Induce la produccion de fitoalexinas y proteinas de defensa, creando una resistencia sistemica adquirida (SAR) contra patogenos.",
    benefits: ["Activa defensas naturales", "Resistencia sistemica", "Reduce uso de fungicidas", "Sin residuos"],
    application: "Aplicar preventivamente cada 10-15 dias. Dosis: 0.5-1 L/ha.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/bioelicitor.jpg",
  },
  {
    id: "10",
    name: "Recento",
    slug: "recento",
    presentation: "Liquido 1L",
    type: "Liquido concentrado",
    description: "Biofortificante que mejora el cuajado de frutos y aumenta la calidad de la cosecha.",
    fullDescription: "Recento es un biofortificante especialmente formulado para mejorar el cuajado, desarrollo y calidad de frutos. Contiene boro, zinc, calcio y extractos vegetales que promueven la formacion de polen viable y el desarrollo uniforme de frutos.",
    benefits: ["Mayor cuajado de frutos", "Frutos uniformes", "Mejor calidad", "Mayor vida de anaquel"],
    application: "Aplicar desde prefloracion hasta desarrollo de fruto. Dosis: 1-2 L/ha.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/recento.jpg",
  },
  // BIOINSECTICIDAS (Bioinsecticidas y Acaricidas)
  {
    id: "11",
    name: "EPA 90",
    slug: "epa-90",
    presentation: "Liquido 1L",
    type: "Liquido emulsionable",
    description: "Bioinsecticida de amplio espectro para el control de plagas de lepidopteros y coleopteros.",
    fullDescription: "EPA 90 es un bioinsecticida a base de extracto de Neem concentrado al 90%. Su ingrediente activo, la azadiractina, actua como regulador del crecimiento, antialimentario y repelente contra una amplia gama de insectos plaga.",
    benefits: ["Amplio espectro", "Multiples modos de accion", "Sin resistencia", "Seguro para polinizadores"],
    application: "Aplicar al observar primeros indicios de plaga. Dosis: 1-2 L/ha. Repetir cada 7-10 dias.",
    category: "BIOINSECTICIDAS",
    image: "/images/products/epa-90.jpg",
  },
  {
    id: "12",
    name: "Ajick",
    slug: "ajick",
    presentation: "Solucion acuosa 1L",
    type: "Solucion acuosa",
    description: "Repelente natural a base de extractos de ajo para el manejo integrado de plagas.",
    fullDescription: "Ajick es un repelente natural formulado con extractos concentrados de ajo (Allium sativum). Sus compuestos azufrados actuan como repelente de insectos y acaros, siendo una herramienta efectiva en programas de manejo integrado de plagas.",
    benefits: ["Repelente natural", "Sin toxicidad", "Compatible con enemigos naturales", "Efecto rapido"],
    application: "Aplicar preventivamente o al detectar primeras plagas. Dosis: 1-2 L/ha cada 5-7 dias.",
    category: "BIOINSECTICIDAS",
    image: "/images/products/ajick.jpg",
  },
  {
    id: "13",
    name: "Azanim",
    slug: "azanim",
    presentation: "Concentrado emulsionable 1L",
    type: "Concentrado emulsionable",
    description: "Insecticida botanico a base de azadiractina para control de insectos chupadores y masticadores.",
    fullDescription: "Azanim es un insecticida botanico de alta pureza a base de azadiractina extraida del arbol de Neem. Controla eficazmente moscas blancas, pulgones, trips, minadores, orugas y otras plagas mediante su accion antialimentaria, reguladora del crecimiento y ovicida.",
    benefits: ["Alta concentracion", "Control de multiples plagas", "Accion ovicida", "Bajo impacto ambiental"],
    application: "Aplicar en aspersion total cubriendo bien el follaje. Dosis: 0.5-1 L/ha.",
    category: "BIOINSECTICIDAS",
    image: "/images/products/azanim.jpg",
  },
  {
    id: "14",
    name: "Capsikron",
    slug: "capsikron",
    presentation: "Liquido 1L",
    type: "Liquido concentrado",
    description: "Bioinsecticida a base de capsaicina con efecto repelente y de contacto.",
    fullDescription: "Capsikron es un bioinsecticida formulado con oleorresina de capsicum (capsaicina). Actua por contacto e ingestion causando irritacion en los insectos, ademas de tener un potente efecto repelente. Efectivo contra pulgones, acaros, trips y orugas.",
    benefits: ["Efecto de contacto", "Fuerte repelencia", "Rapida accion", "Ingrediente natural"],
    application: "Aplicar al atardecer para evitar degradacion. Dosis: 1-1.5 L/ha cada 7 dias.",
    category: "BIOINSECTICIDAS",
    image: "/images/products/capsikron.jpg",
  },
  {
    id: "15",
    name: "Pirelium",
    slug: "pirelium",
    presentation: "Liquido 1L",
    type: "Liquido concentrado",
    description: "Insecticida natural a base de piretrinas para control rapido de plagas.",
    fullDescription: "Pirelium contiene piretrinas naturales extraidas del crisantemo (Chrysanthemum cinerariaefolium). Las piretrinas actuan rapidamente sobre el sistema nervioso de los insectos, causando paralisis y muerte. Ideal para control de emergencia de plagas.",
    benefits: ["Accion de derribe rapida", "Degradacion rapida", "Sin residuos", "Amplio espectro"],
    application: "Aplicar temprano en la manana o al atardecer. Dosis: 0.5-1 L/ha.",
    category: "BIOINSECTICIDAS",
    image: "/images/products/pirelium.jpg",
  },
  {
    id: "16",
    name: "Cinnanim",
    slug: "cinnanim",
    presentation: "Liquido 1L",
    type: "Liquido concentrado",
    description: "Acaricida biologico a base de extracto de canela para el control de acaros fitofagos.",
    fullDescription: "Cinnanim es un acaricida biologico formulado con aceite esencial de canela (Cinnamomum zeylanicum). El cinamaldehido presente actua por contacto sobre acaros fitofagos como la arana roja, acaros blancos y otros acaros que afectan cultivos horticolas y frutales.",
    benefits: ["Especifico para acaros", "Accion de contacto", "Aroma agradable", "Sin periodo de carencia"],
    application: "Aplicar cubriendo bien el enves de las hojas. Dosis: 1-2 L/ha cada 7-10 dias.",
    category: "BIOINSECTICIDAS",
    image: "/images/products/cinnanim.jpg",
  },
]

export const productCategories = [
  { value: "all", label: "Todos los productos" },
  { value: "FUNGICIDAS", label: "Fungicidas" },
  { value: "BIOINSECTICIDAS", label: "Bioinsecticidas" },
  { value: "BIOFORTIFICANTES", label: "Biofortificantes" },
]

export type ProductCategory = "all" | "FUNGICIDAS" | "BIOINSECTICIDAS" | "BIOFORTIFICANTES"

export function getProductBySlug(slug: string) {
  return productsData.find((p) => p.slug === slug)
}

export function getProductById(id: string) {
  return productsData.find((p) => p.id === id)
}
